name: main

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  main:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 5
    steps:
      - name: CommentTest
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "PRへのコメント内容をファイルに出力する" > /tmp/comment
          gh pr comment "${PR_NUMBER}" -F /tmp/comment
