name: Add PR Comment

on:
    pull_request:
        types:
            - opened

jobs:
    add_comment:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
                uses: actions/checkout@v2

            - name: Add PR Comment
                uses: actions/github-script@v4
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    script: |
                        const comment = `Hello, this is a comment added by the GitHub Actions workflow!`;
                        const { data: comments } = await github.issues.listComments({
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: context.issue.number
                        });
                        const existingComment = comments.find(c => c.user.login === 'github-actions[bot]' && c.body === comment);
                        if (!existingComment) {
                            await github.issues.createComment({
                                owner: context.repo.owner,
                                repo: context.repo.repo,
                                issue_number: context.issue.number,
                                body: comment
                            });
                        }